services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID-FAKE
      - AWS_SECRET_ACCESS_KEY=FAKEFAKE